name: Production
on:
  push:
    branches:
      - deploy-on-elb
  pull_request:
    branches:
      - deploy-on-elb

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::519236269948:role/code-perdu-role
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: eu-west-3
      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
      - name: Run deploy.sh
        run: |
          chmod +x deploy.sh
          ./deploy.sh
