name: Production
on:
  push:
    branches:
      - deploy-on-elb
  pull_request:
    branches:
      - deploy-on-elb

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::519236269948:role/github_action
          aws-region: us-west-3
      - name: Run deploy.sh
        run: |
          chmod +x deploy.sh
          ./deploy.sh
